FROM php:8.4-apache

RUN apt-get update && apt-get install -y \
    libsqlite3-dev \
    && docker-php-ext-install pdo pdo_sqlite

WORKDIR /var/www/html

COPY . .

RUN a2enmod rewrite
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
